'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('petOffice', {
  getState: () => ipcRenderer.invoke('state:get'),
  setMouseIgnore: b => ipcRenderer.send('mouse:ignore', b),
  startTask: payload => ipcRenderer.invoke('task:start', payload),
  createMissionDraft: payload => ipcRenderer.invoke('mission:createDraft', payload),
  confirmMission: id => ipcRenderer.invoke('mission:confirm', id),
  regenerateMission: id => ipcRenderer.invoke('mission:regenerate', id),
  cancelMission: id => ipcRenderer.invoke('mission:cancel', id),
  cancelMissionTask: (missionId, taskId) => ipcRenderer.invoke('mission:cancelTask', { missionId, taskId }),
  resumeMission: id => ipcRenderer.invoke('mission:resume', id),
  listMissions: () => ipcRenderer.invoke('mission:list'),
  getMission: id => ipcRenderer.invoke('mission:get', id),
  resolveMission: (missionId, action) => ipcRenderer.invoke('mission:resolveConflict', { missionId, action }),
  startChat: payload => ipcRenderer.invoke('chat:start', payload),
  newChat: payload => ipcRenderer.invoke('chat:new', payload),
  resetChat: payload => ipcRenderer.invoke('chat:reset', payload),
  listSessions: projectId => ipcRenderer.invoke('chat:sessions', projectId),
  handoffChat: taskId => ipcRenderer.invoke('chat:handoff', taskId),
  respondInteraction: payload => ipcRenderer.invoke('interaction:respond', payload),
  cancelTask: id => ipcRenderer.invoke('task:cancel', id),
  createProject: name => ipcRenderer.invoke('project:create', name),
  addProject: () => ipcRenderer.invoke('project:add'),
  selectProject: id => ipcRenderer.invoke('project:select', id),
  renameProject: (id, name) => ipcRenderer.invoke('project:rename', { id, name }),
  archiveProject: (id, archived = true) => ipcRenderer.invoke('project:archive', { id, archived }),
  removeProject: id => ipcRenderer.invoke('project:remove', id),
  clearAttachments: id => ipcRenderer.invoke('project:clearAttachments', id),
  recommendAgents: payload => ipcRenderer.invoke('agents:recommend', payload),
  setSettings: patch => ipcRenderer.invoke('settings:set', patch),
  setUi: patch => ipcRenderer.invoke('ui:set', patch),
  renamePet: (petId, name) => ipcRenderer.invoke('pet:rename', { petId, name }),
  setModel: (petId, model) => ipcRenderer.invoke('pet:model', { petId, model }),
  setSkin: (petId, skin) => ipcRenderer.invoke('pet:skin', { petId, skin }),
  skinData: slug => ipcRenderer.invoke('skin:data', slug),
  refreshSkins: () => ipcRenderer.invoke('skins:refresh'),
  setCap: (petId, cap) => ipcRenderer.invoke('cap:set', { petId, cap }),
  openPath: p => ipcRenderer.invoke('shell:open', p),
  openExternal: url => ipcRenderer.invoke('shell:external', url),
  normalizeLinks: payload => ipcRenderer.invoke('links:normalize', payload || {}),
  startCapture: petId => ipcRenderer.invoke('capture:start', petId || 'supervisor'),
  openCodex: threadId => ipcRenderer.invoke('codex:open', threadId),
  openPetdex: () => ipcRenderer.invoke('petdex:open'),
  pathForFile: file => {
    try {
      const { webUtils } = require('electron');
      if (webUtils && typeof webUtils.getPathForFile === 'function') return webUtils.getPathForFile(file) || null;
    } catch {}
    return (file && file.path) || null;
  },
  ingestFiles: (paths, projectId) => ipcRenderer.invoke('files:ingest', { paths: Array.isArray(paths) ? paths : [], projectId }),
  refreshQuota: () => ipcRenderer.invoke('quota:refresh'),
  diagnostics: () => ipcRenderer.invoke('diagnostics:get'),
  displays: () => ipcRenderer.invoke('desktop:displays'),
  checkUpdates: () => ipcRenderer.invoke('release:check'),
  openRelease: () => ipcRenderer.invoke('release:open'),
  crashStatus: () => ipcRenderer.invoke('crash:status'),
  openCrashes: () => ipcRenderer.invoke('crash:open'),
  reportRendererCrash: payload => ipcRenderer.send('crash:renderer', payload),
  hideApp: () => ipcRenderer.invoke('app:hide'),
  showApp: () => ipcRenderer.invoke('app:show'),
  quit: () => ipcRenderer.invoke('app:quit'),
  on: (ch, fn) => ipcRenderer.on(ch, (e, d) => fn(d)),
});
